#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo 'Running unit tests...'
python3 unit_tests.py 2> unit_test_result 

if grep 'OK' unit_test_result > /dev/null
then 
	echo 'Unit tests is successful'
	rm unit_test_result
	pylint -E /chat/aaamanager.py 2> /dev/null > log.txt
	if  grep "(import-error)" log.txt > /dev/null
	then 
		echo "Quality control tests is failed, you cannot commit"
		exit 1
	else 
		echo "Quality control tests is successful"
		exit 0
	fi
	exit 0 
else 
	echo 'The unit tests is failed, you cannot commit' 
	exit 1 
fi
