#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
echo 'Running unit tests...'
python unit_tests.py 2> unit_test_result 

if grep 'OK' unit_test_result > /dev/null
then 
	echo 'Unit tests is successful'
	rm unit_test_result
	exit 0 
else 
	echo 'The unit tests is failed, you cannot commit' 
	exit 1 
fi
